---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCC1SoD7nYJqi1Gt9mY6qjmi7QBu6JdR1bwKT9iaXIrIft0cSZY/v9W3ms5jQU6xSsq45jm1+7pw2v1ITx9eIuY++2a+eAa8phNXcXyiy3Ud8IF/55ZN0q6Fux31SgsCcCP4LPzG1WomnURR9RehqTAd4+rnBylj8B4wc3B6FshcvnFTw/7oaI/3pR/oKzdecf7+9zi/XLMrKCxJ789W1LBaHlmHu65ons072F3BGe4bw6lpB+eB8efX93C50gEpZfLkvs8TjzDNzWzWJCxadqILmPV2Ub/aIGiJSH6xlqbFZrpJ6qV0tR5zpbW5Ba9uaZQZOAl+RAtUMQwOhYkL3LATnnEftcLlPgyBN11YM7ZV9uXidUKivByxriCQqPfemnRKsJVfxc0KGowNT8pwrEHHALqERubCClt44jatRKw9FHwB94Ou7I1to/AalKKV/73VFvwvsoljxRzBWWOXXUcrAS+aI34mMSe/VBSTrFhvq98V2wcsBDzEx0kN5MFt7lOIajSCXYgWhgNzArSheOVnuKV8GhpwwKjYw3CBTr/Vynm4Pvlig/589+G82wOzuWvsvNohKLEmMkyFWWoevAiYXdPooBg4x/VBajbNEIlQ7bvo5BrLu4QQ5fo8M+QcUEx6GV4ZYFdO4iVj1Wgo30OgZDlQah/Yc4QLrnO9AONS3XCVFPHFLL+OMspiNHlq+2IIbymgJyb0mhWvXhqgKLp3mA4sYt/1kI5HV5X1/ftPqwjDP0=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
