kubeStateMetrics:
  enabled: true  # Keep this enabled

nodeExporter:
  enabled: false  # This disables the node exporter

grafana:
  persistence:
    enabled: true
    storageClassName: synology-iscsi
    size: 10Gi
  adminPassword: ${GRAFANA_ADMIN_PASSWORD}

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: synology-iscsi
          resources:
            requests:
              storage: 50Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: synology-iscsi
          resources:
            requests:
              storage: 10Gi

# Disable node-exporter to avoid PSP issues
prometheus-node-exporter:
  enabled: false
