fullnameOverride: "kube-prometheus-stack"

prometheusOperator:
  admissionWebhooks:
    failurePolicy: Ignore

prometheus:
  prometheusSpec:
    retention: 5d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

grafana:
  persistence:
    enabled: true
    size: 10Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

