apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/phin3has
  services.yaml: |
    - Homelab:
      - Grafana:
            href: http://grafana.phin3has.local
            description: Grafana
            icon: grafana.png
      - Synology:
            href: http://192.168.11.83:5000/
            description: Synology
            icon: synology.png
      - pihole
            url: http://192.168.11.69
            version: 5
            key: 
              valueFrom:
                secretKeyRef:
                  name: pihole-apikey
                  key: apikey

    - Media:
      - Audiobookshelf:
            href: http://audio.phin3has.me
            description: Audio Bookshelf        
            key: 
              valueFrom:
                secretKeyRef:
                  name: audiobookshelf-apikey
                  key: apikey
            icon: audiobookshelf.png
      - Hacker News:
            href: https://news.ycombinator.com/
            description: Hacker News
            icon: commafeed.png
      - YouTube:
            href: https://youtube.com
            description: YouTube
            icon: youtube.png

    - Misc:
      - Linkding:
            href: https://links.phin3has.me/bookmarks
            description: Linkding
            icon: linkding.png
      - N8n:
            href: https://n8n.phin3has.me
            description: N8n
            icon: n8n.png
      - Claude:
            href: https://claude.ai/new
            description: Claude
            icon: mdi-robot-excited-outline-#DE7552
  widgets.yaml: |
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
    - datetime:
        format:
            dateStyle: short
            timeStyle: short
            hour12: true
    - openmeteo:
        label: Brighton
        latitude: 39.91116671277023
        longitude: -104.81402706969988
        timezone: America/Denver
        units: imperial
        cache: 5
        format:
            maximumFractionDigits: 1

  docker.yaml: ""
