apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/phin3has
  services.yaml: |
    - Homelab:
      - Grafana:
            href: http://grafana.phin3has.me
            description: Grafana
            icon: grafana.png
      - Synology:
            href: http://192.168.11.83:5000/
            description: Synology
            icon: synology.png
      - Audiobookshelf
            href: http://audiobookshelf.host.or.ip:port
            description: Audio Bookshelf        

    - Consuming:
      - Hacker News:
            href: https://news.ycombinator.com/
            description: Hacker News
            icon: commafeed.png
      - YouTube:
            href: https://youtube.com
            description: YouTube
            icon: youtube.png

    - Misc:
      - Linkding:
            href: https://links.phin3has.me/bookmarks
            description: Linkding
            icon: linkding.png
      - N8n:
            href: https://n8n.phin3has.me
            description: N8n
            icon: n8n.png
      - Claude:
            href: https://claude.ai/new
            description: Claude
            icon: mdi-robot-excited-outline-#DE7552
  widgets.yaml: |
    - audiobookshelf
        url: http://audiobookshelf.host.or.ip:port
        key: audiobookshelflapikey
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
