---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: traefik
spec:
  encryptedData:
    credentials.json: AgBjtC1FyVpY8E8AzMSA3dfAx32DRwY7JwLQUU0UA236aJbSGwptA1ux/u62GE2MIQ/wgeAuWT/OJuzgIvHZwK2muRTcNnLC0B5EEtsITy2/22peucNN5No0fGFsHtZZV0umMpab1WLJSqOijXbddr6W8pqqd1WLOMyg8sPbPdnMhYlCf43PM506OvgZl89vto+2fe1KokZY75o81hUjShjMuQfOgKM/Xo5RzWegdPlwZySAwGdq5II3edo2H9nU+CIacmEMoHX4f/h1L+hhfSZIlL/JaB7ApUfF9WLciscaSa7iPHam5zNukf11WuCHV2Z58TVXFK2SLs6cKRx6db6Z3DjO0lZYHGx0IgQ/XZOG2Re3L1SmgnH5Ox5iEkXwoa08LLGnMuqxlZ0Fu8P3vHVY3burM38f5zdQS4iUxkkZJTE2OOF7z7VzXs5BPjmqGXnx2Y8dyAEoGeHnZ4/4ms55o3O6auDhN3+NfCE/xwlLZHmTrp+OmhGPEFlyzXbr31fWa1oICdChslhYN5Ngj/krv4/5IXpOV+oOAQTwSyd3rAy12xrt9GVSzaWW8OSNaajW866MjqJtmw+r1XXzbpTuSqZG9fcRdh6bD8UZGwz7lKPNGsY7jAyhlxLetKkMsc+MyYhtzxyIH836BD15LvfmsFzSENjvFOOkrSfj600omr4pQlHwJ4qw4OmJONR4ASAFwWT56tpzojaSmjj3JL7tjUeFYHm5HG2pq94N3NlE5HgjQLf5xCV/iIV82pvKmk0THXgFoDMA/O1ltxgykzbQIFqFh4krABISw4aKYQMEDmPj9O5FWY8CwZZzIyyy8767r7ZoO5BSwqWiommb/j2i5ncq11TtNoTWGYTvy/Buz8tUG9X4B+VPyyON9IbKEeRbXepBY5ccOJ1l5w6rGrlfyg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: traefik
