apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi  # Assuming this is your Synology storage class name
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi  # Assuming this is your Synology storage class name
  resources:
    requests:
      storage: 5Gi
