# storage.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-pvc-synology
  namespace: linkding
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: synology-iscsi
