apiVersion: v1
kind: PersistentVolume
metadata:
  name: linkding-pv
  namespace: linkding
spec:
  capacity:
    storage: 1Gi  # Adjust size as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Adjust based on your cluster's storage classes
  hostPath:  # Consider using a more appropriate storage provider in production
    path: /data/linkding
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-pvc
  namespace: linkding
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
