prometheus:
  alertmanager:
    enabled: true
    persistence:
      enabled: true
      storageClass: "synology-iscsi"
      accessModes:
        - ReadWriteOnce
      size: 10Gi
    statefulSet:
      enabled: true
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: synology-iscsi
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
  
  server:
    persistentVolume:
      enabled: true
      storageClass: "synology-iscsi"
      accessModes:
        - ReadWriteOnce
      size: 50Gi
    
    retention: "15d"
    
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    enableAdminApi: true
    
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
