apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-middleware-authentik
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  project: default
  source:
    repoURL: 'git@github.com:phin3has/homelab.git'
    path: 'infrastructure/networking/middleware'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true