apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: browserless
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:phin3has/homelab.git
    targetRevision: HEAD
    path: apps/browserless
  destination:
    server: https://kubernetes.default.svc
    namespace: browserless
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
