apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: traefik
    server: https://kubernetes.default.svc
  source:
    path: infrastructure/networking/cloudflare-tunnel
    repoURL: git@github.com:phin3has/homelab.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
