apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  sources:
    # Chart from Chart repo
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 8.9.0
      helm:
        valueFiles:
        - $values/infrastructure/monitoring/grafana/values.yaml
    # values from github
    - repoURL: git@github.com:phin3has/homelab.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
