apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    path: ''
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 68.4.5
    chart: kube-prometheus-stack
  destination:
    name: ''
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
