apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkding
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: linkding
    server: https://kubernetes.default.svc
  source:
    path: apps/linkding
    repoURL: git@github.com:phin3has/homelab.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
