apiVersion: apps/v1
kind: Deployment
metadata:
  name: sublime-postgres
  namespace: sublime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sublime-postgres
  template:
    metadata:
      labels:
        app: sublime-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.2
        command: ["-c", "max_connections=200"]
        env:
        - name: POSTGRES_USER
          value: sublime
        - name: POSTGRES_DB
          value: mantis
        - name: PGDATA
          value: /data/postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sublime-secrets
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /data/postgres
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: sublime-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sublime-postgres
  namespace: sublime
spec:
  selector:
    app: sublime-postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sublime-postgres-pvc
  namespace: sublime
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi