# applications/vault.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.27.0  # Specify the Helm chart version you want to use
    helm:
      values: |
        server:
          dev:
            enabled: false  # Enable dev mode for testing - disable in production
          ha:
            enabled: false  # Set to true if you want HA setup
          
          dataStorage:
            size: 10Gi
            storageClass: synology-iscsi
          
          serviceAccount:
            create: true
          
          # Adjust resources as needed
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
          
          # Configure Vault UI
          ui:
            enabled: true
            serviceType: ClusterIP  # Change to LoadBalancer or NodePort if needed
  
  destination:
    server: https://kubernetes.default.svc
    namespace: vault  # Namespace where Vault will be deployed
  
  syncPolicy:
    automated:
      prune: true  # Automatically delete resources that are no longer defined
      selfHeal: true  # Automatically sync if drift is detected
    syncOptions:
      - CreateNamespace=true  # Automatically create the namespace if it doesn't exist

---
# Optional: Create a ConfigMap for additional Vault configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  extraconfig.hcl: |
    ui = true
    
    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
      cluster_address = "[::]:8201"
    }
    
    storage "file" {
      path = "/vault/data"
    }

---
# Optional: Define specific RBAC if needed
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-server-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
