# Global settings
global:
  checknewversion: false
  sendanonymoususage: false

# Deployment specific configuration
deployment:
  enabled: true
  replicas: 2
  annotations: {}
  podAnnotations: {}

# Service configuration
service:
  enabled: true
  type: NodePort
  ports:
    web:
      port: 80
      nodePort: 30596
      protocol: TCP
    websecure:
      port: 443
      nodePort: 30128
      protocol: TCP

# Ports configuration
ports:
  web:
    port: 80
    expose: {}
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose: {}
    exposedPort: 443
    protocol: TCP

# Entry points configuration
entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true

# IngressClass configuration
ingressClass:
  enabled: true
  isDefaultClass: true

# Provider configuration
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: true

# SSL configuration
ssl:
  enabled: false
  https:
    enabled: false

# Persistence configuration
persistence:
  enabled: false

# Resource limits
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "300m"
    memory: "300Mi"

# Security context
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

# Additional arguments
additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--providers.kubernetesingress.ingressclass=traefik"
  - "--log.level=DEBUG"  # Increased log level for troubleshooting
