# Global settings
global:
  checknewversion: false
  sendanonymoususage: false

# Deployment specific configuration
deployment:
  enabled: true
  replicas: 2

# Entry points configuration
entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      enabled: true
      trustedIPs:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: "10s"
      respondingTimeouts:
        readTimeout: "30s"
        writeTimeout: "30s"
        idleTimeout: "60s"

# Service configuration
service:
  enabled: true
  type: NodePort
  annotations: {}
  spec:
    externalTrafficPolicy: Cluster
  ports:
    web:
      port: 80
      nodePort: 30596
      protocol: TCP

# Ports configuration
ports:
  web:
    port: 80
    expose: {}
    exposedPort: 80
    protocol: TCP

# IngressClass configuration
ingressClass:
  enabled: true
  isDefaultClass: true

# Provider configuration
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: true

# Resource limits
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "300m"
    memory: "300Mi"

# Security context
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

# Logs configuration
logs:
  general:
    level: DEBUG
  access:
    enabled: true

# Additional arguments
additionalArguments:
  - "--providers.kubernetesingress.ingressclass=traefik"
  - "--serversTransport.forwardingTimeouts.dialTimeout=30s"
  - "--serversTransport.forwardingTimeouts.responseHeaderTimeout=30s"
