# Traefik Values Configuration
deployment:
  enabled: true
  kind: Deployment
  replicas: 2
  podSecurityContext:
    fsGroup: 65532
  securityContext:
    capabilities:
      drop: []
      add:
        - NET_BIND_SERVICE
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    privileged: true
  annotations:
    container.apparmor.security.beta.kubernetes.io/traefik: "unconfined"
    pod-security.kubernetes.io/enforce: "privileged"
    pod-security.kubernetes.io/audit: "privileged"
    pod-security.kubernetes.io/warn: "privileged"

ingressClass:
  enabled: true
  isDefaultClass: true

# Ports configuration
ports:
  web:
    port: 8000
    expose: {}
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    expose: {}
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true

# Service configuration
service:
  enabled: true
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: true
  spec:
    loadBalancerIP: "10.0.11.100"  # Your MetalLB IP
  ports:
    web:
      port: 80
      protocol: TCP
    websecure:
      port: 443
      protocol: TCP

# Persistent storage configuration
persistence:
  enabled: true
  storageClass: "synology-iscsi"
  accessMode: ReadWriteOnce
  size: 128Mi

# RBAC configuration
rbac:
  enabled: true
  namespaced: false

# Provider configuration
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true

# Resources
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

# Additional arguments
additionalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"
  - "--entryPoints.web.forwardedHeaders.insecure"
  - "--entryPoints.websecure.forwardedHeaders.insecure"

# High Availability settings
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - traefik
          topologyKey: kubernetes.io/hostname

# Tolerations for running on control plane nodes
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
