# Traefik Values Configuration
deployment:
  enabled: true
  kind: Deployment
  replicas: 2

# Pod Security Context
podSecurityContext:
  fsGroup: 65532

# Container Security Context
securityContext:
  capabilities:
    drop: []
    add:
      - NET_BIND_SERVICE
  privileged: true
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false

# Pod annotations for security context
podAnnotations:
  container.apparmor.security.beta.kubernetes.io/traefik: "unconfined"
  pod-security.kubernetes.io/enforce: "privileged"
  pod-security.kubernetes.io/audit: "privileged"
  pod-security.kubernetes.io/warn: "privileged"

# Ports configuration
ports:
  web:
    port: 8000
    expose: {}
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    expose: {}
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true

# Service configuration
service:
  enabled: true
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  spec:
    loadBalancerIP: "10.0.11.100"

# Persistent storage configuration
persistence:
  enabled: true
  name: data
  storageClass: synology-iscsi
  accessMode: ReadWriteOnce
  size: 1Gi

# RBAC configuration
rbac:
  enabled: true
  namespaced: false

# Provider configuration
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true

# Resources
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

# Additional arguments
additionalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"
  - "--entryPoints.web.forwardedHeaders.insecure"
  - "--entryPoints.websecure.forwardedHeaders.insecure"

# Tolerations for running on control plane nodes
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
