# Traefik Values Configuration
deployment:
  enabled: true
  kind: Deployment
  replicas: 2
  # Container security settings at deployment level
  securityContext:
    capabilities:
      drop: []
      add:
        - NET_BIND_SERVICE
    allowPrivilegeEscalation: true
    privileged: true
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false

# Pod Security Context
podSecurityContext:
  fsGroup: 65532

# Pod annotations for security context
podAnnotations:
  container.apparmor.security.beta.kubernetes.io/traefik: "unconfined"
  pod-security.kubernetes.io/enforce: "privileged"
  pod-security.kubernetes.io/audit: "privileged"
  pod-security.kubernetes.io/warn: "privileged"

# Ports configuration
ports:
  web:
    port: 8000
    expose: {}
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    expose: {}
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true

# Service configuration
service:
  enabled: true
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  spec:
    loadBalancerIP: "10.0.11.100"

# Persistence configuration - Using separate volumes for each replica
persistence:
  enabled: false  # Disabled persistent storage initially
  
# RBAC configuration
rbac:
  enabled: true
  namespaced: false

# Resources
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

# Additional arguments
additionalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"
  - "--entryPoints.web.forwardedHeaders.insecure"
  - "--entryPoints.websecure.forwardedHeaders.insecure"

# Node affinity to ensure scheduling on worker nodes
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: DoesNotExist
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - traefik
          topologyKey: kubernetes.io/hostname
