# Traefik Values Configuration
deployment:
  enabled: true
  replicas: 2
  podSecurityContext:
    fsGroup: 65532
  securityContext:
    capabilities:
      drop: []
      add:
        - NET_BIND_SERVICE
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    privileged: true

# Service configuration
service:
  enabled: true
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: true
  spec:
    loadBalancerIP: "10.0.11.100"  # Assign from your MetalLB pool

# Ports configuration
ports:
  web:
    port: 80
    expose: {}
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose: {}
    exposedPort: 443
    protocol: TCP

# Persistent storage configuration for certificates
persistence:
  enabled: true
  storageClass: "synology-iscsi"  # Your Synology iSCSI storage class
  accessMode: ReadWriteOnce
  size: 128Mi

# RBAC configuration
rbac:
  enabled: true
  namespaced: false

# Security settings
additionalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"
  - "--entryPoints.web.forwardedHeaders.insecure"
  - "--entryPoints.websecure.forwardedHeaders.insecure"

# Pod security settings
podSecurityPolicy:
  enabled: true

# Resources
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

# TLS configuration
ssl:
  enabled: true
  enforced: false
  permanentRedirect: false

# Metrics
metrics:
  prometheus:
    enabled: true

# Provider configuration
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true

# Volume mounts for certificates
volumes:
  - name: certificate-storage
    persistentVolumeClaim:
      claimName: traefik-certs

# Tolerations to run on master nodes if needed
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

# Node affinity/anti-affinity rules
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - traefik
          topologyKey: kubernetes.io/hostname
