# Global settings
global:
  checknewversion: false
  sendanonymoususage: false

# Deployment specific configuration
deployment:
  enabled: true
  replicas: 2
  annotations: {}
  podAnnotations: {}

# Health check configuration
healthCheck:
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 2
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 2

# Service configuration for Talos with kube-vip
service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  spec:
    loadBalancerIP: "10.0.11.50"
    externalTrafficPolicy: Local
  ports:
    web:
      port: 80
      exposedPort: 80
      protocol: TCP
    websecure:
      port: 443
      exposedPort: 443
      protocol: TCP
    traefik:
      port: 9000
      exposedPort: 9000
      protocol: TCP

# Ports configuration
ports:
  web:
    port: 80
    expose: {}
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose: {}
    exposedPort: 443
    protocol: TCP
  traefik:
    port: 9000
    expose: {}
    exposedPort: 9000
    protocol: TCP

# IngressClass configuration
ingressClass:
  enabled: true
  isDefaultClass: true

# Provider configuration
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: true

# SSL configuration
ssl:
  enabled: false
  persistence:
    enabled: false
  https:
    enabled: false

# Persistence configuration
persistence:
  enabled: false

# Resource limits
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "300m"
    memory: "300Mi"

# Security context
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

# Metrics
metrics:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

# Dashboard and API configuration
api:
  dashboard: true
  insecure: true

# Additional arguments
additionalArguments:
  - "--api.dashboard=true"
  - "--api.insecure=true"
  - "--ping=true"
  - "--ping.entrypoint=traefik"
  - "--log.level=INFO"
