# Global settings
global:
  checknewversion: false
  sendanonymoususage: false

# Deployment specific configuration
deployment:
  enabled: true
  replicas: 2
  annotations: {}
  podAnnotations: {}

# Service configuration for Talos with kube-vip
service:
  enabled: true
  type: LoadBalancer
  annotations: 
    kube-vip.io/loadbalancerip: "10.0.11.50" # Replace with your desired IP
  spec:
    externalTrafficPolicy: Local
  ports:
    web:
      port: 80
      exposedPort: 80
      protocol: TCP
    websecure:
      port: 443
      exposedPort: 443
      protocol: TCP

# Ports configuration
ports:
  web:
    port: 80
    expose: {}
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose: {}
    exposedPort: 443
    protocol: TCP

# IngressClass configuration
ingressClass:
  enabled: true
  isDefaultClass: true

# Provider configuration
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: true

# SSL configuration
ssl:
  enabled: false  # Disable SSL for now
  persistence:
    enabled: false  # Disable SSL persistence
  https:
    enabled: false  # Disable HTTPS
  acme:
    enabled: false  # Explicitly disable ACME

# Storage configuration - using emptyDir for multi-replica support
persistence:
  enabled: false

# Volume configuration for logs/temp data
volumes:
  - name: temp
    mountPath: /tmp
    type: emptyDir

# Resource limits
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "300m"
    memory: "300Mi"

# Security context
securityContext:
  capabilities:
    drop: [ALL]
