apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns  # Add this line
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.15.1
        args:
        - --source=service
        - --domain-filter=phin3has.me 
        - --provider=cloudflare
        - --request-timeout=1m  # Add this line to handle timeouts
        env:
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-token
              key: apiToken
        - name: CF_API_EMAIL
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-token
              key: email
