---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    apiToken: AgBJ4MW9KWBOIwOC/rFnY8qpTwdM+E3++u48NhhaZq97cxb3jr6V/110qFPSgtwwg2JW1+JGflpje9z0euL2VAUQYI9UGPeZdT8kXu/Wpf3vU6vh/GkkP1KUpUyGe0OHY+QZN93d2hJAeqPZMBVFfKEc/zkYjXkjHMwhu7X4iF+T1UYmgZrGF7DmAcE75RvtwDHGz35QbTA8tldL5y/YYXrRNiklOMkx/Kt/knuq3ZWgi9fD+MERu0tpUM9HW+0Q1iePpC0r/GlqPiu3B/AjXjQhf311+N2HVY1STrIu0MkTpyEV81KAs3az3vSXl3vvZsrhigIZ+GdOaw7xwE9LkUEbf9K9VmqMQAfsDW7k6G+t/8DVvwl/vTRcUBfq11Oo8HkfR/03IAa39cUveYSqYtTsOQ3IXG2B2aLrDipEXkBb/J3kj0PtAO9tV4G+TrEVH7Rw8OlmstKnZtdTeDvGvfyUInXxiUBMYquhdGUMdRL0GjfciakEr6KY+DbX+3oKN0mJ9g5FmmrDNoefPgvlwzpK8zu196rXMHdASBDz2k5pbdCSvP3AxiqpmRyfFtaNuzYSSz5HL687C3ZBX2YeKyDtVZL1HVfHGq1QaBQDMhaDxcuLLtA0xvcmOUXhx9x+sDQ0rKEEMMrOCvD3RY2FBVsERBv6KktZGtK5lNbWG0buYOXFvJ21HxvIRCn42wR6utq8VXb53yYXnujL5fROJptV9ctQgtkMmLE8FMG8nSk+OPYaOMJm78PW
    email: AgBxKuYUbyHxrxONk2rCouRuQlAIG+d7OpN20EIKMAPbjniC2pIRWYgCK++95BBb/a9viSw0cccvVShJ11xNCrGyNB0pdRyGVx5B1hz6p9qKO/D4Tj/MCql2uxWJUN3RI3VKfWLEiNSn34dAhRIlYMdtxrRpZBtqsf3L89bXf1O1xjEKW05VfMXkx/EKxNlIa+gNbiCs7KwAZRGTxbE1kWQ2OBdNrLi5PVvjFnBdfJmGouLkO4mUGDQFZ+3oAVz0aUein+HGihElO3Tb0cJiq63YhXsb1pJX23SisRFZHVmqucXTjpqCIbqUTPTnKOrZfynv8F2aNG/5Jj0YQNjGju6vEFLfsAy02GluiE1rsqVMw3Kjco07hyAEB8LfixI5AtUApSByNFx6g+R/g9VGxRaahBY9nd7mnVv0PcbwrlNf8HIQ+r6XXnHNU0G484M8ZiceQvDqF0nGc5+tY1aPMiBc1IzmyEgOqMG1pq6zwclsiNSxcjA95xE/ppPcXMSZDt4h5zp1+lRcZy8tUTCi7wUBbtjFg0Mjz+1hR1/+x4I3gRV/2ZmftxjhATHmI7FVfplTHyCbqj/OaRDoq3xu7fYst0IW2qBrgEqBskDB/AlbcamvtXr6rwv2DRgwbQEh4hsAlCwZI4LTNH6plr78rVNTYa3m4WrHQ02x67BT8ddqGw6JNXtI+uRtyHI64+OkqihhwPnODC4S9dgCbrFfrLPYpFrQfqVuY3k=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
