sealed-secrets:
  # Global settings for sealed-secrets
  fullnameOverride: sealed-secrets-controller
  
  secretName: "sealed-secrets-key"  # This is the default name
  secretAnnotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/compare-options: IgnoreExtraneous

  # Controller settings
  controller:
    # You can customize the controller settings here
    create: true
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    
    # Service settings
    service:
      type: ClusterIP
      port: 8080

