apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-new-data
  namespace: hoarder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-iscsi
