---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hoarder-secrets
  namespace: hoarder
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgCQ+SZaQdyxGZOSLoGgIL6Yi4NKHn1k3QRpXRDl4Qg8Gog8XPOuBpbBlh92ut2hwWwm/2i0B2xfGXVIIIyvmvmLU4Ax2G6qojMrODeclboiFsU0i3iiP38NIeAYqI6uxoSuFjsN1aikISclHW93iN9jEgwEii7Qyit8twzQ7Krl46k+xKnG726PgJ0ECIvqIMnbro6SAbwzQrDLw8+zja7/UvlpdwgQIgBWoDeMjPp4y7vSocKgHEppFN+iEEe/dxZgZCrAuZKFgQd9YppFnIM5iVa94MgRXsGPynMVM2mWpmWxQZeucqmPaLBAZryxhAhqfKShRTszU58a+rml6VFKIZtpKZk5kQ8nYqmlx6Zf3AXVTkLGyYfSd3iKJCeSN4PbUKVAJyt1SnJbmfEWH3ahA8LxOWLSx3KRxREIZjyQQX0jEIqTdupu9hRGQpEtgFT0suNeauyJgk+gWJPoUPWLTeJ+LaCRZRauf/rRcvlEnR7+AEz3uEqLimas/izhHoksZST/NgknhoofweU220HojfYveG4UlgdoPQGzWzT3q58GoziZ//2XhPIKdgrPpGqKD8pHZdJv+RblbvKVJovnCfS0U0/aE7CI3wAb99W6hm3bTGlchH62o9XJJ9MuZrt5WcNO2Lrcw4K/PqxQei3JUiTmIYJCqEr3ov/1rbK7/lFqmUYNXSMSB2WR5EbuGDiKMgMBdevtVsOUH8+UVimEA2gjlqVvqyoU5sM=
    OPENAI_API_KEY: AgCoDnPD9isxGP8N+/tsrD6U2NN4FotDI4MnrFGeCjNgT3oHK0L9GtsbBirstYw8u2vPzQhLIFAks+moEYd+iKiXDFrzr+pisOteAlY4K/KJAS1ilUxcyRQHuSpqT15cqkLSIvdNzmsOLdax7ya5o+8nsPN9wMPcCpTFh8nzyP94y9PrGJjn593MXhgeR2u2ipoptoPd5oHWXyT9rD4t6ISHYW9YMzhGZiJh91lddOImZQqUrQclaqLpMXdqbXVa+YWvsYRo8nwXzFGxrmTZrIiY4IlfVgHRhmzRFtuyneEDe7avriOT7zp3kv+qZH2vQ21hFQdb6CfPl51Lp579F3QaqF8MawQ2SDCgHPaZIhKmrMFlQdv22LZD//WhtgQjuODaSTY2u01idUYTWaZ13T3RtF8HYMPAjnGQBcDL7meU8gHxcNycyDAdzyGxtIM2s741NBTnTAFKMApRvxDI6T1+KLIW3HdMLDdkTQy6x48B175nRFD3vZac7Hpzzb0w/cr4AIHytv/E95SZpPEmw/55NDuqJ6pbnYxi0caeHna09hlRAWPIMTpIg0YGrNWiX6/RLm+sH2cTqhP9TvYMiaeE91urLV4eFaQR/qOgI2MgY6wMm4Z6QHoHOQpGt4tn1S932WEfMVVZTtU4yxom2Teq8BkVuYsHb5+JmRPGB3xuoD2YIEZl264DtK5kXmLoNUA8+jjnAd7zxkVqQSSqcjH+u/bTvIMhB/6n9w6yN0dTe514gs4XVThDDQ4BXtS0+jwoUr+cHU+XQL6JhK9YnsbX8LtElqUqo/Mxh0bRW/sXjnNEuIsLnILVEUuDZiLGbIq6fApHE2sMkdVSQaoY+9WtJB5FkGnchWNKLGC4NTJIPgbXZDMo+o4hZMtXD9MLO7UPCfjBP1ej6M+t1aKvCXYQwfEE1w==
  template:
    metadata:
      creationTimestamp: null
      name: hoarder-secrets
      namespace: hoarder
