apiVersion: v2
name: grafana
description: Grafana for homelab
type: application
version: 0.1.0
dependencies:
  - name: grafana
    version: 8.9.0
    repository: https://grafana.github.io/helm-charts
