---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBEodcw/7qkcytUhvsnpxFtRiVAENuYZXZjhe+Rsv5lpzpensQVBQq4a3tX8plcm3//rv7pNbK53MwjRAE7K0drTDyn5AJY8oc0VjlblNsKl7pFMg9fPp888t2WloL5gdHiD5v/nfWhPVxpq/YVF0GfzuB4VIR2+62MJKSK6VD1lC7IBojiIMOFwoxYRwk1BtZA7hZe84ifSfCcI9nuq7zNIDgR9c6hNSQ1T94l1E3U5t8GBg5YUJffbmMlGu6Qz82f/drfzAL/V4bGJlISC1NBpZM9MKHlE6YJNdUAr7mWkmhOqIEfxzY3hkNCYoNNgpATsscVh7/Vd2cwDRPf86bdQ8CUk6Da6pJ6dCmctRZ2aqM8sXBO9fd4fSQbPmPcHbFP9JuzxPNTpwQiuZOjEV7DfKUpfYImRoal8kCMHtdGgeDXdzB7b1kgVHrsOPVWo9zBjQE+zq5VB8Pe4NH2AW+u+bh2zQi7eh1w9napbAbKACflpbGnDmk52GbHD7kw7WPArBZMqErV+chfS2azmdhmW+eK8R2qW/SLDEOUZBk1s3dSb3xRsTNLe1mMGMF5P1YeDgSz6cwScLRPH7mHyxc2M8ekWZqNnL8OavYt2mB64eL0fwh0QC4taI5f++ooDTrfbac5FarEaMSCxhTj15eMF3pJPtoJBYn1YrOaA1NAmvxco6hDGFIctBR5ctjPq6OQ0NHArBdr1HF5JnjBcEiClJy8kl7hHATqyEZXSsBbJqQK6j4=
    admin-user: AgCFjet3k3Deq7k6KpYpjXWg03qYAyO6s4u/tHJgDeonCBol+0p720YeQDY6lgTztYvkgb3ynNsC2iM4Gtj2Zfes+HYVOayQQsVGekRBWdNHrmAmCUs1oBlv6DK8cIf0ZPfWqFBoyaOdM539i2mD/DSC/vJtmsaoN0BFvMvCHNdje2ZWYzdqjqGwdW4G+Az0+yWlu9gG5Jz3oZttn82okpz0h2FZu4NClrp7waqY692LnOixCNQH9bTfzRgct7VJXecu0ClNUIA+sPang/liD+94cWbElwSLMukxLFLKpaIRfg1uQm8Kk5FYpzSC9cAcPfxleM7UdauwwWAPG42NrWQjTpsZ+tfkAmqOANK1nDLC5u4aeYI+T8njaVNeBJVcpV6QlP9A9M9qPmZJVIGQ/SOzR+XytLdq6n6vN0URdc9EpyMtIAUau7XnWL5JiZX2it0USELOhAGYH0rXIE9h9w20E1iq9LTkhBJcXSA9YOKm/62r0IEhvHc4vo2UvY2xEffH1ZtJTcOwENhRSQpcDvgAWu+7Z2fHOckQeDO55V3V05DDRye2pKTq7dkKGR7o4bHnn6ELH23fFZK70zdtkRtJl38BDIsxjtLIf48k5fkDCQNYi0YrqKZTHMfCeb0dbuAAX9Zh33DWlcch1JIJ301GX174O0lVprA/aEv4U+sBXBhjEjNs0MZfjsoFTdekyer8qt+hYw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
