loki:
  auth_enabled: false
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules

  config:                       # Added config section to properly structure the settings
    storage_config:            # Moved under config
      filesystem:
        directory: /var/loki/chunks

    schema_config:             # Moved under config
      configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    limits_config:             # Moved under config
      allow_structured_metadata: false

    compactor:                 # Added compactor config for TSDB
      working_directory: /var/loki/compactor
      shared_store: filesystem

deploymentMode: "SingleBinary<->SimpleScalable"

singleBinary:
  enabled: true
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClass: synology-iscsi
    accessModes:
      - ReadWriteOnce

# Set replicas to 0 for other components
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
ruler:
  replicas: 0
