# Set single binary mode with filesystem storage
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: boltdb-shipper
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

# Use single deployment mode
singleBinary:
  enabled: true
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClass: synology-iscsi
    accessModes:
      - ReadWriteOnce

# Explicitly disable the scalable deployment modes
read:
  enabled: false
write:
  enabled: false
backend:
  enabled: false

# Disable optional components
monitoring:
  lokiCanary:
    enabled: false
gateway:
  enabled: false
