loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    filesystem:
      directory: /var/loki/chunks
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: boltdb-shipper
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  limits_config:
    allow_structured_metadata: false

deploymentMode: "single-binary"  # Changed to explicitly use "single-binary"

# Configure single binary mode
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClass: synology-iscsi
    accessModes:
      - ReadWriteOnce
  podSecurityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001

# Explicitly disable all scalable components
querier:
  replicas: 0
distributor:
  replicas: 0
ingester:
  replicas: 0
queryFrontend:
  replicas: 0

# Disable unnecessary components
canary:
  enabled: false
sidecar:
  enabled: false
gateway:
  enabled: false
monitoring:
  selfMonitoring:
    enabled:

