loki:
  storage:
    type: filesystem
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    filesystem:
      directory: /var/loki/chunks
  auth_enabled: false

write:
  enabled: false
read:
  enabled: false
backend:
  enabled: false

singleBinary:
  enabled: true
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClass: synology-iscsi
    accessModes:
      - ReadWriteOnce
