loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    filesystem:
      directory: /var/loki/chunks
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: boltdb-shipper
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  limits_config:
    allow_structured_metadata: false

deploymentMode: "single"  # Changed to just "single"

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClass: synology-iscsi
    accessModes:
      - ReadWriteOnce

# Disable everything else
backend:
  enabled: false
gateway:
  enabled: false
ingester:
  enabled: false
canary:
  enabled: false
querier:
  enabled: false
queryFrontend:
  enabled: false
ruler:
  enabled: false
distributor:
  enabled: false
monitoring:
  enabled: false
