loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    filesystem:
      directory: /var/loki/chunks
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: boltdb-shipper
        object_store: filesystem
        schema: v13  # Updated from v12
        index:
          prefix: index_
          period: 24h
  limits_config:
    allow_structured_metadata: false  # Added this to address the error

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClass: synology-iscsi
    accessModes:
      - ReadWriteOnce

# Disable canary
canary:
  enabled: false

# Disable sidecar
sidecar:
  enabled: false

serviceMonitor:
  enabled: true

# Disable all other components
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ruler:
  replicas: 0
