loki:
  auth_enabled: false
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules

deploymentMode: "SingleBinary<->SimpleScalable"  # Changed to transitional mode

singleBinary:
  enabled: true
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClass: synology-iscsi
    accessModes:
      - ReadWriteOnce

# Set replicas to 0 for all other components
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
ruler:
  replicas: 0
