deploymentMode: SingleBinary<->SimpleScalable

loki:
  storage:
    type: filesystem
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    filesystem:
      directory: /var/loki/chunks
  auth_enabled: false

write:
  enabled: false
  replicas: 0    # Explicitly set to 0
read:
  enabled: false
  replicas: 0    # Explicitly set to 0
backend:
  enabled: false
  replicas: 0    # Explicitly set to 0

singleBinary:
  enabled: true
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClass: synology-iscsi
    accessModes:
      - ReadWriteOnce
