# MetalLB Helm Values
controller:
  enabled: true
  logLevel: info
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi

speaker:
  enabled: true
  logLevel: info
  frr:
    enabled: false  # Explicitly disable FRR
  bgp:
    enabled: false  # Explicitly disable BGP
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi

rbac:
  create: true

prometheus:
  serviceMonitor:
    enabled: false
  podMonitor:
    enabled: false

crds:
  enabled: true
  validationFailurePolicy: Fail
  # Do not cleanup CRDs on uninstall to prevent CA bundle issues
  cleanupOnUninstall: false

webhookConfig:
  enable: false  # Disable webhook to avoid CA bundle issues
  timeoutSeconds: 5
  failurePolicy: Fail
