# MetalLB Helm Values
controller:
  enabled: true
  logLevel: info
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi

speaker:
  enabled: true
  logLevel: info
  frr:
    enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi

rbac:
  create: true

prometheus:
  serviceMonitor:
    enabled: false
  podMonitor:
    enabled: false

crds:
  enabled: true
  validationFailurePolicy: Fail

webhookConfig:
  enable: true
  timeoutSeconds: 5
  failurePolicy: Fail
