apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
spec:
  destination:
    name: ''
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: apps/apps
    repoURL: git@github.com:phin3has/homelab.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

