authentik:
    # Secret key will be provided by sealed secret
    secret_key: "${SECRET_KEY}"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: true
    postgresql:
        # Password will be provided by sealed secret
        password: "${POSTGRESQL_PASSWORD}"

server:
    ingress:
        # Specify kubernetes ingress controller class name
        ingressClassName: traefik
        enabled: true
        hosts:
            - auth.phin3has.me
        annotations:
            external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
            external-dns.alpha.kubernetes.io/hostname: auth.phin3has.me
            external-dns.alpha.kubernetes.io/target: 54e08de2-5664-48f1-8fa4-26580666989f.cfargotunnel.com

postgresql:
    enabled: true
    auth:
        # Password will be provided by sealed secret
        password: "${POSTGRESQL_PASSWORD}"
redis:
    enabled: true