---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    postgresql-password: AgAAOnQjs/SMdH8TJX1SpBv7MrhoCXm4Jy7G0HwexivDA/R6Llv8YvwYWT0GmrNzr7BINT4VS3M3SSzA/Rgvp5sNuQiDHLeqZAs8CERLVgK5t9i1Ke43ulYUwAbAnQ+tEN83hM/RdjHO8yDyugG/RO6x4DMqcEFw5Kn+bU9qna2Vs0DSdCTwUz+F4joggQ8HwzK8Vx2OY3WZhLUhJ4i+Q/YJyQoJ26k1lDHsplipZmIQPwx/JIfsWANyZBA5XHFYijMKYel0RIMtGqMBQQ5Ob3rTtsscjXa/loObrdy3Njr8k3CSWH8L4P43OPZfyu2FrQ4drZZc2WQ+Rxkb+H8Ykm45gLxUwabXZq6Ddc9pp4T/vM2URCjLpC/0YX8DjjU/P+UW0KBBF0/HdHnhwyiIloeua/+l9IOabiM2SgLc5Hun8Xfp1VyqDQpt6scY70g9xN8n1Ky9nZ02bYA940vwMEAZNzidvbIYYJEiYDsG6ePLMLQATC4bOuF4KJcspNL2Rw0KIBR/r4P0CBwKdkgWD4YZIDR8KSSzXeL4fMWm1B+q8wFggRCqyRO7WlZkfVKeFcyiYLdr8kdqndJrk2bJjtPESVpvk0go9Pwxx/23rn9+JFA2xQD6bGwGuYLJxHMCOESA7czqqvng5KOTuT08K7KwqSsqKidKNvJDuBRRE3Jn+PjoIdZ2P/AFJqrczhv9xlPgUe5d3FJLuad+5d0K3/X13N5SBPFw4kP1fEk=
    secret_key: AgAWBMcblbxfYOWPkxhNLyQdeDVKiUPktglkkJLVpTZ9TS49u9eVmmFB9jNQ/RNZskCPboRG4PnH2tDgMH8NzutkBwng46mIlAuRjLaZ1Hd1pePft3xSEqCzf8p4J7iZ2U1C3vveTeUbeT/ZLSmhFUgdBfKS/vTf/XoDVA9m/J6t2VTYOKd3owVMa8qmw4wdJc5Af6JbkMJoSttM+mvcEAGpftZqxVFe4EuNt9Ngw+axo/tZwl/BKWYpkOjZr1J8JfEso4n3xryNIDG1qgtMKsSq6ADlJFe8bVHu1t3jNVNBWdGO8chRFMAgzTtZW+QxPkGbBB2XQRZ9eM/BbTeMGLqXg0n9nGsWXimgatdElhQ6WLQsKTw+npFo8PVsOh9OSRp7fNsf3Q/tHRJi15jbwCR5E4ck3dzIGH87y9JshgXCLpzWq3SCwcyC+GdDtVKhy0n19xw8WEW30RgqEGhloso0ywRWzKrHXfXey1u+5E3xaPExRVyljpwnOeKQOrdcv3mzTo2WbCBS/tGfzemCuigQTdAkFDZFwmjji1QZ0sICDTkTpvaLARpwynhZ0ym+CwdkaZyHVhAtOHRKD2sLCX/oulR4+Kydr7BcWDR7aYyxXX7MTlsS3N42pTJlHGGsVGcag38V+gTQxUYPnsTgt41S3A1+fAEk6HZZHjyEhAhgxqQlh1BWDKBpqW3mNyOYia1CFV8amzxVwttxxhWLFCXx6UItSiGy8AhaxUyR
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secrets
      namespace: authentik
