apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-helm-values
  namespace: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Ensure this is created before Helm chart is installed
data:
  SECRET_KEY: '{{ lookup "v1" "Secret" "traefik" "authentik-secrets" | jsonPath "{.data.secret_key}" | base64decode }}'
  POSTGRESQL_PASSWORD: '{{ lookup "v1" "Secret" "traefik" "authentik-secrets" | jsonPath "{.data.postgresql-password}" | base64decode }}'