apiVersion: ENC[AES256_GCM,data:6QM=,iv:SlGG3SoWOBgGFT51vIkremI1PcwVF0o39euymnlyRYc=,tag:c5BcHF/5qoteTYtCuG0aeg==,type:str]
kind: ENC[AES256_GCM,data:yx3yHjZ+,iv:pueB/rh3y4iusMkxVkgFcLIxGjxrKs4XC+ninYJeyDM=,tag:6dHvwGysqKhH1BGvOiRW9Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:J5zUuh2H8ZV51kM=,iv:v0X3SJpuysUuQSf39mAQBTYRrsJYmnyXq9SojkvdbU0=,tag:gq78Pak0vP2sXR+QNTN5Pw==,type:str]
    namespace: ENC[AES256_GCM,data:GRrZPG0sZw==,iv:xbyXkvjMl7LWgCVimEzSzKQMTyHcp7EycCm33w/KUUc=,tag:L4y647xXK5kYcEbzQO+U3w==,type:str]
type: ENC[AES256_GCM,data:0TBLtMgW,iv:YIUOPHzbSD3B7H48PTtOmr81xozFab4imCv9ILzYD7g=,tag:tWkZmnjozSnri/NMXSFOiw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:4oEe9EI=,iv:oWUn48Ilp80p4Tw1tUElsuCD7z1q1wRl8uhNERK7YXo=,tag:4GJfQPhdQyHgnrn86w+55A==,type:str]
    password: ENC[AES256_GCM,data:ke8B9nyCnquH6hQ=,iv:zatHLhjChmdCuqTmuqKfCC/rFiWI0IvVoEOCbQLouXU=,tag:dHRnO3s2Egjl8HD4GED/MA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18ld6zg4lyhacddgmpc3zm44elcmzaccel73fefcwlrtg7ene0y4s8mtstr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YWJYeFV3TWNBWHV4NTZB
            NFlhVWJJWkVQbkw1MXdZc3JQZ2tzb2lORDJzCjYxazZzaWdUbzVLWTc2VXVJeGd4
            SWFNangvZjd3UXlaczBuM2U5WDl6S28KLS0tIG55VmlzQnFmN0FvNDFaS2MzR0ZK
            bWFKd2o5RDBNWDZqMk12U3dnT2xENWcKN16wH5Cm3PsG1A0E3fGWmrfcl5NA4WGw
            fV4+Gh5nTLV77ryBpVSLB4Jgkdd4jz9d0481UHSprUDV7ynCtXYecA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T01:29:05Z"
    mac: ENC[AES256_GCM,data:RJbCOmBBr7A8gRjN0aWi0FSiBTrKOcP0/g1W4PfaZVZiczc9e1FuNw5UMp8ugxTgUgmyPwu/FAi1TX5IZAkozy9yzuX1pBCKWYl/gcB1cRR3tvDoyskz33NeuLo2vmgaMwQCK/DoqtH79Ij8+Jbg8eUHb6B4bv2UgQzFErB/C0o=,iv:tAqtyP8OjHgZAcg9Vpn3mp5Rh4unWyb/CqdGOLNoSqs=,tag:NXB8X4IAow3hEmF4m+36vA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
